Salesforce/Marketing Cloud/Scenario_1/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Less Than ₹1,00,000</fullName>
                </value>
                <value>
                    <fullName>In Between ₹1,00,000 to ₹5,00,000</fullName>
                </value>
                <value>
                    <fullName>Greater Than ₹5,00,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <label>Primary</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SICCode__c</fullName>
        <label>SIC Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Salesforce/Marketing Cloud/Scenario_1/classes/LeadSICCodeTest.cls
@isTest
private class LeadSICCodeTest {
    @testsetup
	private static void TestData()
    {
        List<Lead> leadList = New List<Lead>();
        Lead ld = new Lead();
        ld.FirstName = 'Akash';
        ld.LastName = 'Bangalkar';
        ld.Status = 'New';
        ld.Company = 'FlexaNet';
        ld.Budget__c = 'Greater Than ₹5,00,000';
        
        leadList.add(ld);
        
        Insert leadList;
    }
    
    @isTest
    private static void testMethod1()
    {
        List<Lead> ldList = [SELECT ID, Primary__c FROM Lead];
        
        for(Lead ld:ldList)
        {
            ld.Primary__c = 'Yes';
        }
        
        Test.startTest();
        Update ldList;
        Test.stopTest();
        
        List<Lead> ldCheck = [SELECT ID, SICCode__c FROM Lead WHERE SICCode__c!=NULL];
        System.assertEquals(1, ldCheck.size());
    }
}