Salesforce/Sales Cloud/Scenario_1/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Saving</fullName>
        <active>true</active>
        <label>Saving</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset__c.object
<CustomObject>
   <fields>
      <fullName>Asset_Type__c</fullName>
      <label>Asset Type</label>
      <type>Picklist</type>
      <valueSet>
         <restricted>true</restricted>
         <valueSetDefinition>
            <value>
               <fullName>Current Ac</fullName>
            </value>
            <value>
               <fullName>Saving Ac</fullName>
            </value>
            <value>
               <fullName>Fix Deposit</fullName>
            </value>
         </valueSetDefinition>
      </valueSet>
   </fields>
   <label>Asset</label>
   <nameField>
      <displayFormat>FD-{DD}{0}</displayFormat>
      <label>Asset Number</label>
      <type>AutoNumber</type>
   </nameField>
   <pluralLabel>Assets</pluralLabel>
   <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/Marketing Cloud/Scenario_2/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Less Than ₹1,00,000</fullName>
                </value>
                <value>
                    <fullName>In Between ₹1,00,000 to ₹5,00,000</fullName>
                </value>
                <value>
                    <fullName>Greater Than ₹5,00,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <label>Primary</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SICCode__c</fullName>
        <label>SIC Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/LeadSICCodeTest.cls
@isTest
private class LeadSICCodeTest {
    @testsetup
	private static void TestData()
    {
        List<Lead> leadList = New List<Lead>();
        Lead ld = new Lead();
        ld.FirstName = 'Akash';
        ld.LastName = 'Bangalkar';
        ld.Status = 'New';
        ld.Company = 'FlexaNet';
        ld.Budget__c = 'Greater Than ₹5,00,000';
        
        leadList.add(ld);
        
        Insert leadList;
        
        Asset__c ass1 = New Asset__c();
        ass1.Asset_Type__c = 'Saving Account';
        ass1.Lead__c = ld.Id;
        
        Insert ass1;
    }
    
    @isTest
    private static void testMethod1()
    {
        List<Lead> ldList = [SELECT ID, Primary__c FROM Lead];
        
        for(Lead ld:ldList)
        {
            ld.Primary__c = 'Yes';
        }
        
        Test.startTest();
        Update ldList;
        Test.stopTest();
        
        List<Lead> ldCheck = [SELECT ID, SICCode__c FROM Lead WHERE SICCode__c!=NULL];
        System.assertEquals(1, ldCheck.size());
        
        List<Asset__c> asCheck = [SELECT ID, Asset_Available__c FROM Asset__c WHERE Asset_Available__c = TRUE];
        System.assertEquals(1, asCheck.size());

    }
}