Salesforce/Marketing Cloud/Scenario_3/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Employee_Required__c</fullName>
        <label>Employee Required</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Est_End_Date__c</fullName>
        <label>Est End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Java</fullName>
                </value>
                <value>
                    <fullName>Python</fullName>
                </value>
                <value>
                    <fullName>SF Admin</fullName>
                </value>
                <value>
                    <fullName>SF Dev</fullName>
                </value>
                <value>
                    <fullName>JS</fullName>
                </value>
                <value>
                    <fullName>CSS</fullName>
                </value>
                <value>
                    <fullName>HTML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityController.cls
public with sharing class OpportunityController {
	public static void CreateProjectRecord(List<Opportunity>oppList, Map<Id,Opportunity>oldMap)
    {
        List<Project__c> projRec = New List<Project__c>();
        for(Opportunity opp:oppList)
        {
            if(opp.StageName=='Value Proposition' && opp.StageName != oldMap.get(opp.Id).StageName)
            {
                Project__c proj = New Project__c();
                proj.Name = opp.Name;
                proj.Skills__c = opp.Skills__c;
                proj.Start_Date__c = opp.Start_Date__c;
                proj.Est_End_Date__c = opp.Estimated_End_Date__c;
                proj.Employee_Required__c = opp.No_of_Employee__c;
                proj.Project_Status__c = 'New';
                
                projRec.add(proj);
            }
        }
        
        if(projRec.size()>0)
        {
            Insert projRec;
        }
    }
}